### ISSUE TITLE
how to get a smooth trackpad?

### ISSUE THREAD

**Issue by Joanromanoo** [JaemanPratama/Hackintosh-Asus-A455LA-X455LA-Broadwell-SERIES#6]
how do I get a smooth trackpad scroll like you? BTW thank you for the trackpad gesture you give

**Comment by JaemanPratama** [comment]
Anda harus mengedit info.plist yang terdapat pada appleps2smarttouchpad.kext,  **terutama yang dibagian scroling**

![Screen Shot 2022-07-04 at 13 40 23](https://user-images.githubusercontent.com/89202419/177096364-83582c7f-caaf-46fc-9444-183ad3832b15.png)

Dan anda juga harus menyesuaikan `2FContScrollMaxDelta` `2FScrollAccelMode` `ScrollSmoothSamples` `InertialScrollDelay``InertialScrollDepth` `ScrollDirectionSamples` `ScrollLevelFactor` `ScrollLevelGranularity``ScrollMaxIdleDetectTimeout` `ScrollMaxIdleStateDelta` `ScrollResolution` dan `ScrollStopDetectSamples` sesuai kebutuhan anda sendiri
